[window]
decorations = "none"
startup_mode = "Maximized"

[terminal.shell]
# To launch Zellij directly, it must be the program. 
# You can't have both 'nu' and 'zellij' as the primary program.
program = "/usr/bin/zellij"

[font]
size = 12.0

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.italic]
family = "Fira Code Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Fira Code Nerd Font"
style = "Bold Italic"   
